# Generated by Django 5.0.2 on 2024-02-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
