# Generated by Django 5.0.2 on 2024-02-19 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storebackend', '0003_product_category_product_price_product_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
